### ISSUE TITLE
ใส่ชื่อใน License ให้ครบคน

### ISSUE THREAD

**Issue by srakrn** [AyumiizZ/SoftengProject#101]

**Comment by AyumiizZ** [comment]
ขอโทษครับ... ไอ้ที่ใส่ไปมมันคือ auto license ของตัว github ครับ ผมยังไม่ได้อ่านมากครับ

**Comment by AyumiizZ** [comment]
#104 ทำให้เเล้ว ลองเช็คด้วยครับ

**Comment by AyumiizZ** [comment]
มีใครเช็คยังครับ

**Comment by srakrn** [comment]
เช็คละครับ กราบ
