### ISSUE TITLE
แก้หน้า jobs/browse ให้แสดงชนิดของงาน

### ISSUE THREAD

**Issue by worachai3** [AyumiizZ/SoftengProject#102]
ตอนนี้ใน database ตาราง jobs ไม่มี job_type แล้วเปลี่ยนเป็น column fixed, hourly เก็บเป็น integer แทน

**Comment by AyumiizZ** [comment]
ทำไมถึงต้องเพิ่มอีกตั้ง 2 column เลยอะ? และในอันเดิม ตาราง jobs ก็มี job_type อยู่เเล้วนิ ถึงจะเก็บเป็น string ก็ไม่น่าจะเเปลกมาก ถ้าจะแก้ ทางที่ดีควรจะแก้ job_type เป็น int แล้วเก็บแบบ 1 เป็น fix 2 เป็น hour หรือเปล่า

**Comment by worachai3** [comment]
ถ้าทำงั้นมันเอาไป query เลยไม่ได้ อีกอย่างใน json ก็แยกเป็น fix กับ hour อยู่แล้วก็เลยเพิ่ม column มาให้มันเอาไป query เลยได้สะดวกกว่า
