### ISSUE TITLE
Bug หน้าโปรไฟล์

### ISSUE THREAD

**Issue by SoLiare** [AyumiizZ/SoftengProject#118]
ถ้าเข้าหน้าโปรไฟล์จากหน้าฟรีแลนซ์ที่สนใจงาน หน้างานที่ผ่านมากับรีวิวจะดูไม่ได้ครับ (/username/ หาย)

**Comment by srakrn** [comment]
Merge with #119, thanks!

**Comment by morganmox** [comment]
อีหยังวะ
