### ISSUE TITLE
Phpmyadmin เข้าไม่ได้

### ISSUE THREAD

**Issue by AyumiizZ** [AyumiizZ/SoftengProject#89]
พอเซ็ต proxy ไปที่ 3000 เเล้วทำให้เปิด nodejs ที่รันไว้ที่ port 3000 ได้ เเต่ phpmyadmin ที่ทำไว้มันดันเปิดไม่ได้เนี่ยสิ ควรจะเเก้ยังไงดี (Jenkins ที่เปิดไว้ที่ port 8080 เข้าได้เฉย)
![screenshot from 2018-11-10 22-30-22](https://user-images.githubusercontent.com/23733936/48303071-3d0d2100-e538-11e8-992f-7b8172af7f64.png)

**Comment by srakrn** [comment]
เซ็ต nginx/apache2 ให้เข้า PHPMyAdmin ตอนพยายามเข้าผ่าน subdomain อื่น

เวลา redirect มัน redirect ไปทั้ง subdomain เลยจะทำแบบนี้ไม่ได้

**Comment by srakrn** [comment]
Is this resolved?

**Comment by AyumiizZ** [comment]
ยังๆ ลืมทำไปเลย ขอโทษครับ

**Comment by AyumiizZ** [comment]
ใช้ได้แล้วครับ
