### ISSUE TITLE
Make reCAPTCHA work

### ISSUE THREAD

**Issue by AyumiizZ** [AyumiizZ/SoftengProject#90]
ตอนนี้ recaptcha ยังไม่สามารถใช้งานได้
![screenshot from 2018-11-13 16-21-08](https://user-images.githubusercontent.com/23733936/48403298-2cd78a80-e760-11e8-87b3-3e92f2ee4db2.png)

**Comment by srakrn** [comment]
reCAPTCHA v3 implemented.
