### ISSUE TITLE
หน้า โปรเจคของฉัน

### ISSUE THREAD

**Issue by AyumiizZ** [AyumiizZ/SoftengProject#92]
หน้าโปรเจ็คของฉัน อยากให้เป็นหน้าที่รวมงานที่ผ่านไปแล้ว เเละเมื่อคลิกเข้าไปจะไปสามารถเข้าไปดุ review โดย client ได้

**Comment by srakrn** [comment]
เขียนหน้าไว้แล้ว เหลือเขียนโค้ด
ไม่น่ายาก eager load จาก model มาได้อยู่แล้วนี่

**Comment by SoLiare** [comment]
เปลี่ยนหน้านี้เป็นดูแนวดูงานทั้งหมด ตั้งแต่เสร็จแล้วยันค้าง+งานที่ไปจ้างชาวบ้านบ่จ๊ะ (เอาไว้เป็นหน้ายืนยันส่งงานไรงี้)
