### ISSUE TITLE
ย้าย branch หลักตัวที่ deploy ในเซิฟ

### ISSUE THREAD

**Issue by AyumiizZ** [AyumiizZ/SoftengProject#95]
จะย้ายจาก deploy ใน dev เป็น deploy ใน master
ซึ่งจะ merge pull request  #96 จาก dev เข้า master
ดังนั้น ขอความกรุณา เช็คว่าส่วนที่ตนเองได้ทำใน dev จะทำให้บัคใน master ไหม

=== จะ Merge ตอนช่วง 19:00 หรือช่วงดึกๆ ของวันที่ 15 พย ===

**Comment by srakrn** [comment]
ถ้า dev ไม่บึ้ม master ก็ไม่ควรบุึ้มมป่ะ 5555555

**Comment by AyumiizZ** [comment]
@srakrn จริงๆ ทำเพื่อเป็นการชี้เเจงครับ เนื่องจากว่าการย้าย Branch หลักในการ deploy อ่านจะกระทบกับงานบางส่วนครับ
